### ISSUE TITLE
Is it possible to set string userId ?

### ISSUE THREAD

**Issue by gotokatsuya** [appannie/ab-testing#37]
Hi. Thanks for sharing your awesome work.

Should I change type `number | string` if it can a string or a number ?

https://github.com/appannie/ab-testing/blob/master/packages/ab-testing/src/index.ts#L56

**Comment by ZigZagT** [comment]
Yeah, we can add support for `string`. The `userId` parameter is ultimately used by the [getModuloValue](https://github.com/appannie/ab-testing/blob/master/packages/ab-testing/src/index.ts#L25) function, it works with any stringish value.

**Comment by SBoudrias** [comment]
Want to send a PR?

**Comment by gotokatsuya** [comment]
OK. I just fork !

**Comment by ZigZagT** [comment]
PR is merged.
The Publish action seems broken now. I'll fix it and publish a release very soon.
