### ISSUE TITLE
v1.2.2 publish?

### ISSUE THREAD

**Issue by bsmith-self** [appannie/ab-testing#46]
Is v1.2.2 expected to make it to NPM soon? We're needing this fix and I'd rather not link to github directly:
https://github.com/appannie/ab-testing/commit/b43b713eb5c4d10973d82b11609c903691d36965

Thanks!

**Comment by ZigZagT** [comment]
1.2.2 is on NPM now.

**Comment by bsmith-self** [comment]
Thank you!
